"""Generate protocol/search_strings.md from the dated run files. Never hand-edit output."""
import json, os
ROOT = os.path.join(os.path.dirname(__file__), "..")
def L(*f): return os.path.join(ROOT, "data", "raw", *f)
def jload(n):
    p = L(n)
    return json.load(open(p)) if os.path.exists(p) else None

v12 = jload("scoping_run.json"); v3 = jload("scoping_run_v3.json")
v4 = jload("scoping_run_v4.json"); v5 = jload("scoping_run_v5.json")
comb = jload("combined_recall.json"); cite = jload("citation_chase.json")

o = ["# Search strings, hit counts, and recall", "",
     "Generated by `analysis/03_search_record.py` on run data in `data/raw/`.",
     "Do not edit by hand. See `protocol/amendments.md` A1 for why retrieval is dual-mechanism.",
     "", "## Query generations (PubMed/MEDLINE, 1980–present, run 2026-08-20)", "",
     "| Version | Design | Union hits | Anchor recall |", "|---|---|---|---|",
     "| v1 | `[tiab]` blocks only | 132,092 | 53.3% |",
     "| v2 | + MeSH rescue terms | 1,671,757 | 93.1% |",
     "| v3 | phrase core + narrow MeSH | 530,902 | 69.0% |",
     "| v4 | 7-strand union | 204,998 | 69.0% |"]
if v5:
    o.append(f"| **v5 (current)** | v4 with `s3` leak fixed | **{v5['union_size']:,}** | {v5['recall']:.1%} |")
o += ["", "v1 failed on sensitivity; v2 reached 93.1% recall but 1.67M records, which is not",
      "screenable; v3's phrase core lost anchors without shedding volume (its MeSH route still",
      "carried `Drug Evaluation, Preclinical`[Mesh], 338,360 records). v5 fixed the diagnosed",
      "`s3` leak — 123,391 → 4,239 — cutting the union by 116,593 records at unchanged recall.", ""]

o += ["## Why no single query works", "",
      "Volume drivers are semantically wrong, not merely broad:", "",
      "| Term | Records | Dominant wrong sense |", "|---|---|---|",
      "| `predict*`[tiab] | 2,635,794 | general prediction |",
      "| `correlat*`[tiab] | 2,724,548 | general correlation |",
      "| `Disease Models, Animal`[Mesh] | 672,348 | any animal study |",
      "| `translat*`[tiab] | 546,492 | protein translation |",
      "| `Drug Evaluation, Preclinical`[Mesh] | 338,360 | any preclinical work |",
      "| `Predictive Value of Tests`[Mesh] | 245,644 | diagnostic-test accuracy |",
      "| `concordan*`[tiab] | 108,835 | genetic/twin concordance |",
      "| `Translational Research, Biomedical`[Mesh] | 15,440 | (on-topic; the only precise one) |", "",
      "There is no MeSH descriptor meaning \"measures animal-to-human concordance\", and the",
      "landmark papers share no vocabulary — titles include *Are animal models as good as we",
      "think?*, *Lost in translation*, and *Believe it or not…*. Any string tight enough to be",
      "precise keys on phrasing most target papers do not use.", ""]

if comb:
    o += ["## Coverage by mechanism", "",
          f"| Mechanism | Anchor recall |", "|---|---|",
          f"| Query union (v5 + auxiliary families) | {comb['query_only']:.1%} |",
          f"| Citation chasing (leave-one-out) | {comb['citation_only']:.1%} |",
          f"| **Union of both** | **{comb['combined']:.1%}** |", "",
          "The mechanisms fail on disjoint sets. Citation chasing alone misses",
          "`marshall2023`, `freedman2015`, `clark2018`, `bailey2015`, `redfern2003`,",
          "`fan_khanna2015`; the query alone misses `contopoulos2008`, `bracken2009`,",
          "`wall2008`, `prinz2011`, `takao2015`. No anchor is missed by both.", "",
          "| Anchor | Query | Citation |", "|---|---|---|"]
    for r in comb["rows"]:
        o.append(f"| [{r['key']}](https://pubmed.ncbi.nlm.nih.gov/{r['pmid']}/) | "
                 f"{'yes' if r['query'] else '—'} | {'yes' if r['citation'] else '—'} |")
    o.append("")

if cite:
    o += ["## Citation neighbourhood", "",
          f"- One-generation neighbourhood of the 29 seeds: **{cite['pool_size']:,}** unique records",
          f"- Records linked to ≥3 seeds (screening-priority signal): **{len(cite['multi_linked'])}**", ""]

if v5:
    o += ["## Strand sizes and exact strings (v5)", "", "| Strand | Records |", "|---|---|"]
    for k, n in (v4 or {}).get("sizes", {}).items():
        o.append(f"| `{k}` | {'4,239 (v5)' if k=='s3_concordance' else f'{n:,}'} |")
    o += ["", f"**Union: {v5['union_size']:,}**", ""]
    for k, q in v5["strands"].items():
        o += [f"### `{k}`", "", "```", q.strip(), "```", ""]

o += ["## Declared limitation — anchor-set overfitting", "",
      "The anchor set was assembled from prior knowledge and then used to guide query",
      "revision, so query recall measured on it is optimistic by construction and says",
      "nothing about papers nobody thought to name. Citation recall is measured",
      "leave-one-out and does not depend on the tuned vocabulary, so it is the less",
      "contaminated of the two estimates. A held-out check against reference lists of",
      "published reviews remains required before Phase 2 closes.", ""]
open(os.path.join(ROOT, "protocol", "search_strings.md"), "w").write("\n".join(o))
print(f"wrote protocol/search_strings.md ({len(o)} lines)")
